[workspace]
authors = ["Horace Guy <horace.guy.k@gmail.com>"]
channels = ["conda-forge"]
name = "resume"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build = "./scripts/build.bash"
deploy = "./scripts/deploy.bash"
all = [{ task = "build" }, { task = "deploy" }]

[dependencies]
pandoc = ">=3.9,<4"
pnpm = ">=10.30.3,<11"
